/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer User
 */
public class AlgorithmDesign extends javax.swing.JFrame {

    /**
     * Creates new form AlgorithmDesign
     */
    public AlgorithmDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblFactorial = new javax.swing.JLabel();
        txtFactorial = new javax.swing.JTextField();
        btnFactorial = new javax.swing.JButton();
        lblPrime = new javax.swing.JLabel();
        txtPrime = new javax.swing.JTextField();
        btnPrime = new javax.swing.JButton();
        lblFibonacci = new javax.swing.JLabel();
        txtFibonacci = new javax.swing.JTextField();
        btnFibonacci = new javax.swing.JButton();
        lblFactorialDisp = new javax.swing.JLabel();
        lblFibonacciDisp = new javax.swing.JLabel();
        lblPrimeDisp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("NUMBERS");

        lblFactorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFactorial.setText("Enter a numberr and click the button to find the factorial.");

        txtFactorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnFactorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFactorial.setText("Factorial");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        lblPrime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPrime.setText("Enter a numberr and click the button to determine whether or not it is a prime number.");

        txtPrime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnPrime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrime.setText("Prime");
        btnPrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeActionPerformed(evt);
            }
        });

        lblFibonacci.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFibonacci.setText("Enter a numberr and click the button to see the correspoding Fibonacci Number.");

        txtFibonacci.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnFibonacci.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFibonacci.setText("Fibonacci");
        btnFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibonacciActionPerformed(evt);
            }
        });

        lblFactorialDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFactorialDisp.setText("...");

        lblFibonacciDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFibonacciDisp.setText("...");

        lblPrimeDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPrimeDisp.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(btnFibonacci)
                        .addGap(71, 71, 71)
                        .addComponent(lblFibonacciDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)
                                .addComponent(btnPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(lblPrimeDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)
                                .addComponent(btnFactorial)
                                .addGap(81, 81, 81)
                                .addComponent(lblFactorialDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPrime, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addComponent(lblFactorial)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial)
                    .addComponent(lblFactorialDisp))
                .addGap(60, 60, 60)
                .addComponent(lblPrime)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrime)
                    .addComponent(lblPrimeDisp))
                .addGap(69, 69, 69)
                .addComponent(lblFibonacci)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFibonacci)
                    .addComponent(lblFibonacciDisp))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findFactorial(int factorial)
    { 
         if(factorial<0)
        {
             txtFactorial.setText("");
             lblFactorialDisp.setText("");
             return;
        }
        
        if(factorial==0)
        {
             lblFactorialDisp.setText("1");
             return;
        }
        
        
        for(int i=factorial-1;i>0;i--)
        {
            factorial = factorial * i;
        }
        lblFactorialDisp.setText(String.valueOf(factorial));
    
    }
    
    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        // TODO add your handling code here:
        int factorial;
        
        try
        {
            factorial = Integer.parseInt(txtFactorial.getText());
        }
        catch(Exception e)
        {   
            txtFactorial.setText("");
            lblFactorialDisp.setText("");
            return;
        }
        findFactorial(factorial);
       
        
        
    }//GEN-LAST:event_btnFactorialActionPerformed

    
     private void determinePrime(int num)
    {  
        
        
        int temp;
        boolean isPrime=true;
       
        if(num<=1)
        {
             isPrime = false;
        }
        else
        {
            for(int i=2;i<=num/2;i++)
            {
                temp = num % i;

                if(temp==0)
                {
                    isPrime = false;
                    break;
                }

            }
        }
        
        
        lblPrimeDisp.setText(String.valueOf(isPrime));
    
    }
    
    private void btnPrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeActionPerformed
        // TODO add your handling code here:
        
        int num;
        
        try
        {
            num = Integer.parseInt(txtPrime.getText());
        }
        catch(Exception e)
        {   
            txtPrime.setText("");
            lblPrimeDisp.setText("");
            return;
        }
        determinePrime(num);
        
    }//GEN-LAST:event_btnPrimeActionPerformed

    
    
    private void determineFibonacci(int num)
    {
        if (num<1)
        {
           txtFibonacci.setText("");
           lblFibonacciDisp.setText("");
           return; 
        }
        
        int xn1 = 0;
        int xn2 = 1;
        int xn = 0;
        
        if(num==1)
        {
            xn = xn1;
        
        }
        else if(num==2)
        {
            xn = xn2;
        }
        else
        { 
            for(int i=3; i<=num; i++)
            {
                xn = xn1 + xn2; 
                xn1 = xn2;
                xn2 = xn;

            }
        } 
        lblFibonacciDisp.setText(String.valueOf(xn));
    }
       
    private void btnFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibonacciActionPerformed
        // TODO add your handling code here:
        int num;
        
        try
        {
            num = Integer.parseInt(txtFibonacci.getText());
        }
        catch(Exception e)
        {   
            txtFibonacci.setText("");
            lblFibonacciDisp.setText("");
            return;
        }
        determineFibonacci(num);
        
        
        
    }//GEN-LAST:event_btnFibonacciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlgorithmDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlgorithmDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnFibonacci;
    private javax.swing.JButton btnPrime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFactorial;
    private javax.swing.JLabel lblFactorialDisp;
    private javax.swing.JLabel lblFibonacci;
    private javax.swing.JLabel lblFibonacciDisp;
    private javax.swing.JLabel lblPrime;
    private javax.swing.JLabel lblPrimeDisp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFactorial;
    private javax.swing.JTextField txtFibonacci;
    private javax.swing.JTextField txtPrime;
    // End of variables declaration//GEN-END:variables

    
}
